-- AlterTable
ALTER TABLE "public"."DETALLES_REGISTRO_DESCARGA_FRUTA_PARA_PROCESO" ADD COLUMN     "muestra_id" INTEGER;

-- AddForeignKey
ALTER TABLE "public"."DETALLES_REGISTRO_DESCARGA_FRUTA_PARA_PROCESO" ADD CONSTRAINT "DETALLES_REGISTRO_DESCARGA_FRUTA_PARA_PROCESO_muestra_id_fkey" FOREIGN KEY ("muestra_id") REFERENCES "public"."MUESTREOS"("id") ON DELETE SET NULL ON UPDATE CASCADE;
